version: "3.9"

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"  # HTTPSのポートも公開
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - web
      - api
      - auth
    networks:
      - app-net

  auth:
    build: 
      context: ./auth
      dockerfile: Dockerfile
    expose:
      - 4000
    env_file:
      - .env   
    networks:
      - app-net


  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    expose:
    - 8080
    networks:
        - app-net


  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    expose:
      - 3000
    env_file:
      - .env
    networks:
      - app-net


  db:
    image: postgres
    container_name: db
    expose:
      - 5432
    environment:
      - POSTGRES_DB=${DB_NAME:-db}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-postgres}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks: 
      - app-net
  adminer:
    image: michalhosna/adminer
    container_name: adminer
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      ADMINER_SERVER: db
      ADMINER_DRIVER: pgsql
      ADMINER_DB: ${DB_NAME:-db}
      ADMINER_USERNAME: ${DB_USER:-postgres}
      ADMINER_PASSWORD: ${DB_PASS:-postgres}
      ADMINER_NAME: Adminer for PostgreSQL DB
    networks:
      - app-net
volumes:
  redis-data:


networks:
  app-net:
    driver: bridge