version: "3.9"

services:
  web:
    build: .
    ports:
      - "80:8443"
      - "443:8443"
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
volumes:
  db-data:
