version: "3.9"

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"  # HTTPSのポートも公開
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - web
      - api
      - auth

  auth:
    build: 
      context: ./auth
      dockerfile: Dockerfile
    expose:
      - 4000
    env_file:
      - .env   
 


  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    expose:
    - 8080


  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    expose:
      - 3000
    env_file:
      - .env


  db:
    image: postgres
    container_name: db
    expose:
      - 5432
    environment:
      - POSTGRES_DB=${DB_NAME:-db}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-postgres}
    volumes:
      - ./db:/docker-entrypoint-initdb.d

