import { Thread } from '@/types/thread';

export const MAPBOX_CONFIG = {
  CENTER: [136.918320, 35.157171] as [number, number],
  ZOOM: 15.27,
  PITCH: 42,
  BEARING: -50,
  STYLE: 'mapbox://styles/mapbox/standard',
  MIN_ZOOM: 5,
  MAX_ZOOM: 50,
  LANGUAGE: 'ja',
  LIGHT_PRESET: 'dusk'
} as const;

export const POPUP_CONFIG = {
  ANCHOR: 'bottom' as const,
  OFFSET: [0, -10] as [number, number],
  CLOSE_BUTTON: false,
  CLOSE_ON_CLICK: false,
  CLASS_NAME: 'custom-popup'
} as const;

export const THREADS_DATA: Thread[] = [
  {
    id: 1,
    coordinates: [136.918320, 35.157171],
    message: "こんちには",
    author: "ユーザー1",
    timestamp: "14:30:25",
    replyCount: 3,
    replies: [
      { id: 1, message: "こんにちは！", author: "ユーザーA", timestamp: "14:31:10" },
      { id: 2, message: "今日は良い天気ですね", author: "ユーザーB", timestamp: "14:32:15" },
      { id: 3, message: "はじめまして", author: "ユーザーC", timestamp: "14:33:20" }
    ]
  },
  {
    id: 2,
    coordinates: [136.920320, 35.158171],
    message: "名古屋駅周辺はとても便利ですね！",
    author: "ユーザー2",
    timestamp: "14:35:12",
    replyCount: 1,
    replies: [
      { id: 1, message: "本当にそうですね！交通の便が良いです", author: "ユーザーD", timestamp: "14:36:05" }
    ]
  },
  {
    id: 3,
    coordinates: [136.916320, 35.156171],
    message: "今日は良い天気です☀️",
    author: "ユーザー3",
    timestamp: "14:40:33",
    replyCount: 5,
    replies: [
      { id: 1, message: "本当に気持ちいいですね", author: "ユーザーX", timestamp: "14:41:00" },
      { id: 2, message: "散歩日和です", author: "ユーザーY", timestamp: "14:41:30" },
      { id: 3, message: "写真撮影にも最適", author: "ユーザーZ", timestamp: "14:42:00" },
      { id: 4, message: "外に出たくなります", author: "ユーザーW", timestamp: "14:42:30" },
      { id: 5, message: "青空が綺麗です", author: "ユーザーV", timestamp: "14:43:00" }
    ]
  },
  {
    id: 4,
    coordinates: [136.919320, 35.159171],
    message: "お疲れ様です！",
    author: "ユーザー4",
    timestamp: "14:45:10",
    replyCount: 0,
    replies: []
  },
  {
    id: 5,
    coordinates: [136.917320, 35.155171],
    message: "この場所おすすめです✨",
    author: "ユーザー5",
    timestamp: "14:50:45",
    replyCount: 2,
    replies: [
      { id: 1, message: "どんなところがおすすめですか？", author: "ユーザーJ", timestamp: "14:51:00" },
      { id: 2, message: "今度行ってみます！", author: "ユーザーK", timestamp: "14:51:30" }
    ]
  }
];

export const LABEL_LAYERS = [
  'country-label',
  'state-label', 
  'settlement-label',
  'settlement-subdivision-label',
  'place-label',
  'poi-label',
  'road-label',
  'water-label',
  'airport-label',
  'transit-label',
  'building-label',
  'natural-label',
  'boundary-label',
  'waterway-label',
  'rail-label',
  'bridge-label',
  'tunnel-label',
  'ferry-label',
  'aerialway-label',
  'cable-car-label',
  'subway-label',
  'bus-label',
  'parking-label',
  'hospital-label',
  'school-label',
  'university-label',
  'library-label',
  'museum-label',
  'theatre-label',
  'cinema-label',
  'restaurant-label',
  'cafe-label',
  'bar-label',
  'hotel-label',
  'shop-label',
  'bank-label',
  'post-office-label',
  'police-label',
  'fire-station-label',
  'church-label',
  'temple-label',
  'shrine-label',
  'mosque-label',
  'synagogue-label',
  'cemetery-label',
  'park-label',
  'playground-label',
  'sports-centre-label',
  'stadium-label',
  'swimming-pool-label',
  'golf-course-label',
  'tennis-court-label',
  'football-pitch-label',
  'baseball-field-label',
  'basketball-court-label',
  'volleyball-court-label',
  'table-tennis-label',
  'badminton-court-label',
  'squash-court-label',
  'bowling-alley-label',
  'fitness-centre-label',
  'gym-label',
  'yoga-studio-label',
  'dance-studio-label',
  'martial-arts-label',
  'climbing-wall-label',
  'ice-rink-label',
  'ski-slope-label',
  'snow-park-label',
  'beach-label',
  'marina-label',
  'harbour-label',
  'port-label',
  'airport-terminal-label',
  'helipad-label',
  'gas-station-label',
  'charging-station-label',
  'car-wash-label',
  'car-rental-label',
  'taxi-stand-label',
  'bus-station-label',
  'train-station-label',
  'subway-station-label',
  'tram-stop-label',
  'ferry-terminal-label',
  'cable-car-station-label',
  'aerialway-station-label',
  'bicycle-parking-label',
  'bicycle-rental-label',
  'motorcycle-parking-label',
  'car-parking-label',
  'truck-parking-label',
  'rv-parking-label',
  'boat-parking-label',
  'airplane-parking-label',
  'helicopter-parking-label',
  'bicycle-shop-label',
  'motorcycle-shop-label',
  'car-dealer-label',
  'truck-dealer-label',
  'boat-dealer-label',
  'airplane-dealer-label',
  'helicopter-dealer-label',
  'bicycle-repair-label',
  'motorcycle-repair-label',
  'car-repair-label',
  'truck-repair-label',
  'boat-repair-label',
  'airplane-repair-label',
  'helicopter-repair-label'
] as const;
