import { Thread } from '@/types/thread';

export const MAPBOX_CONFIG = {
  CENTER: [136.918320, 35.157171] as [number, number],
  ZOOM: 15.27,
  PITCH: 42,
  BEARING: -50,
  STYLE: 'mapbox://styles/mapbox/standard',
  MIN_ZOOM: 5,
  MAX_ZOOM: 50,
  LANGUAGE: 'ja',
  LIGHT_PRESET: 'dusk'
} as const;

export const POPUP_CONFIG = {
  ANCHOR: 'center' as const,
  OFFSET: [0, 0] as [number, number],
  CLOSE_BUTTON: false,
  CLOSE_ON_CLICK: false,
  CLASS_NAME: 'custom-popup'
} as const;

export const THREADS_DATA: Thread[] = [

];

export const LABEL_LAYERS = [
  'country-label',
  'state-label', 
  'settlement-label',
  'settlement-subdivision-label',
  'place-label',
  'poi-label',
  'road-label',
  'water-label',
  'airport-label',
  'transit-label',
  'building-label',
  'natural-label',
  'boundary-label',
  'waterway-label',
  'rail-label',
  'bridge-label',
  'tunnel-label',
  'ferry-label',
  'aerialway-label',
  'cable-car-label',
  'subway-label',
  'bus-label',
  'parking-label',
  'hospital-label',
  'school-label',
  'university-label',
  'library-label',
  'museum-label',
  'theatre-label',
  'cinema-label',
  'restaurant-label',
  'cafe-label',
  'bar-label',
  'hotel-label',
  'shop-label',
  'bank-label',
  'post-office-label',
  'police-label',
  'fire-station-label',
  'church-label',
  'temple-label',
  'shrine-label',
  'mosque-label',
  'synagogue-label',
  'cemetery-label',
  'park-label',
  'playground-label',
  'sports-centre-label',
  'stadium-label',
  'swimming-pool-label',
  'golf-course-label',
  'tennis-court-label',
  'football-pitch-label',
  'baseball-field-label',
  'basketball-court-label',
  'volleyball-court-label',
  'table-tennis-label',
  'badminton-court-label',
  'squash-court-label',
  'bowling-alley-label',
  'fitness-centre-label',
  'gym-label',
  'yoga-studio-label',
  'dance-studio-label',
  'martial-arts-label',
  'climbing-wall-label',
  'ice-rink-label',
  'ski-slope-label',
  'snow-park-label',
  'beach-label',
  'marina-label',
  'harbour-label',
  'port-label',
  'airport-terminal-label',
  'helipad-label',
  'gas-station-label',
  'charging-station-label',
  'car-wash-label',
  'car-rental-label',
  'taxi-stand-label',
  'bus-station-label',
  'train-station-label',
  'subway-station-label',
  'tram-stop-label',
  'ferry-terminal-label',
  'cable-car-station-label',
  'aerialway-station-label',
  'bicycle-parking-label',
  'bicycle-rental-label',
  'motorcycle-parking-label',
  'car-parking-label',
  'truck-parking-label',
  'rv-parking-label',
  'boat-parking-label',
  'airplane-parking-label',
  'helicopter-parking-label',
  'bicycle-shop-label',
  'motorcycle-shop-label',
  'car-dealer-label',
  'truck-dealer-label',
  'boat-dealer-label',
  'airplane-dealer-label',
  'helicopter-dealer-label',
  'bicycle-repair-label',
  'motorcycle-repair-label',
  'car-repair-label',
  'truck-repair-label',
  'boat-repair-label',
  'airplane-repair-label',
  'helicopter-repair-label'
] as const;
