openapi: 3.0.3
info:
  title: Message API
  version: 1.0.0
  description: |-
    This is CHAP's web server. Feel free to use it to store any data you like.
  termsOfService: https://localhost/
  contact:
    email: kazuki175209@gmail.com

servers:
  - url: https://localhost/api
    description: Local API Server (TLS)

paths:
  /message:
    post:
      summary: 新しい投稿を追加
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MapObject'
      responses:
        '200':
          description: 投稿が正常に処理された
        '400':
          description: 不正なリクエスト
        '405':
          description: メソッドが許可されていない

  /search_around_post:
    post:
      summary: 近くの投稿を取得
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Coordinate'
      responses:
        '200':
          description: 投稿のリストを返す
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MapObject'
        '400':
          description: 不正なリクエスト
        '500':
          description: サーバーエラー

  /search_userid:
    post:
      summary: ユーザーIDでユーザー情報を取得
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: integer
      responses:
        '200':
          description: 該当ユーザーを返す
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: 不正なリクエスト
        '500':
          description: サーバーエラー

components:
  schemas:
    User:
      type: object
      properties:
        ID:
          type: integer
        Name:
          type: string
        Email:
          type: string
        Password:
          type: string
    MapObject:
      type: object
      properties:
        ID:
          type: integer
        Content:
          type: string
        CreatedTime:
          type: string
          format: date-time
        Lat:
          type: number
          format: float
        Lng:
          type: number
          format: float
    Coordinate:
      type: object
      properties:
        Lat:
          type: number
        Lng:
          type: number
